---
title: "Evaluate mlflx"
author: "Beni Stocker"
date: "5/22/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(patchwork)
library(ggrepel)
```

## Comparison to physical model


Load out-of-bag (OOB) cross validation results from Stocker et al. (2020) (file `df_metrics_oob_stocker20gmd_fig2.csv`), and from the LSTM.
```{r cars}
df_oob_pmodel <- read_csv("~/mlflx/data/df_metrics_oob_stocker20gmd_fig2.csv")
df_oob_mlflx <- read_csv("~/mlflx/data/lstm_100e_r2.csv") %>% 
  rename(rsq = R2, site = Site)
```

Plot histograms of R-squared of OOB-CV for the two.
```{r pressure, echo=FALSE}
gg1 <- df_oob_pmodel %>% 
  ggplot() +
  geom_histogram(aes(x = rsq, y = ..count..),
    color = "black", alpha = 0.3, binwidth = 0.05, 
    position="identity") +
  theme_classic() +
  labs(x = bquote(italic(R)^2), y = "Count") +
  xlim(0.2, 1)

gg2 <- df_oob_mlflx %>% 
  ggplot() +
  geom_histogram(aes(x = rsq, y = ..count..),
    color = "black", alpha = 0.3, binwidth = 0.05, 
    position="identity") +
  theme_classic() +
  labs(x = bquote(italic(R)^2), y = "Count") +
  xlim(0.2, 1)

gg1 / gg2
```

This is the plot I sent through Slack.
```{r pressure, echo=FALSE}
df <- df_oob_pmodel %>% 
  rename(rsq_pmodel = rsq) %>% 
  full_join(df_oob_mlflx %>% rename(rsq_ml = rsq), by = "site")

df %>% 
  ggplot(aes(x = rsq_pmodel, y = rsq_ml, label = site)) +
  geom_point(size = 2, color = "red") +
  theme_classic() +
  geom_abline(slope = 1, intercept = 0, linetype = "dotted") +
  xlim(0, 1) + ylim(0, 1) +
  geom_text_repel(min.segment.length = 0, seed = 42, box.padding = 0.5) +
  labs(x = bquote("Physical model" ~ italic(R)^2), y = bquote("ML" ~ italic(R)^2))

ggsave("~/mlflx/fig/rsq_oob_comparison.pdf", width = 5, height = 4)
```


This is something else I did for myself (beni).
```{r}
# df_mlflx <- read_csv("~/mlflx/data/ddf_combined_mlflx_20210510.csv")
# 
# df_mlflx %>% 
#   dplyr::filter(classid == "DBF") %>% 
#   pull(sitename) %>% 
#   unique()
# 
# df_mlflx %>% 
#   dplyr::filter(sitename == "US-Var") %>% 
#   slice(2000:3600) %>% 
#   ggplot(aes(x = date)) +
#   geom_line(aes(y = GPP_NT_VUT_REF))
# 
# df_mlflx %>% 
#   dplyr::filter(sitename == "US-Var") %>% 
#   slice(2000:3600) %>% 
#   ggplot(aes(x = date)) +
#   geom_line(aes(y = fpar))

df_metrics <- df_mlflx %>% 
  dplyr::filter(sitename == "FR-Pue") %>% 
  yardstick::metrics("fpar", "GPP_NT_VUT_REF") %>% 
  mutate(sitename = "FR-Pue") %>% 
  bind_rows(
    df_mlflx %>% 
      dplyr::filter(sitename == "CH-Lae") %>% 
      yardstick::metrics("fpar", "GPP_NT_VUT_REF") %>% 
      mutate(sitename = "CH-Lae")
  ) %>% 
  dplyr::filter(.metric == "rsq") %>% 
  mutate(.estimate = format(.estimate, digits = 2))

gg1 <- df_mlflx %>% 
  dplyr::filter(sitename == "CH-Lae") %>% 
  ggplot(aes(y = GPP_NT_VUT_REF, x = fpar)) +
  geom_hex(bins = 30) +
  scale_fill_gradientn(
    colours = colorRampPalette( c("gray65", "navy", "red", "yellow"))(5)
    # , trans = "log", breaks = c(1, 10)
    ) +
  theme_classic() +
  labs(
    title = "Deciduous forest: CH-Lae", 
    subtitle = bquote( italic(R)^2 == .(df_metrics %>% dplyr::filter( sitename == "CH-Lae") %>% pull(.estimate))),
    y = expression(paste("GPP (gC m"^-2, "s"^-1, ")")), x = "MODIS EVI") +
  theme_classic() + 
  geom_smooth(method='lm', color="red", size=0.5, se=FALSE)

gg2 <- df_mlflx %>% 
  dplyr::filter(sitename == "FR-Pue") %>% 
  ggplot(aes(y = GPP_NT_VUT_REF, x = fpar)) +
  geom_hex(bins = 30) +
  scale_fill_gradientn(
    colours = colorRampPalette( c("gray65", "navy", "red", "yellow"))(5)
    # , trans = "log", breaks = c(1, 10)
    ) +
  theme_classic() +
  labs(
    title = "Evergreen forest: FR-Pue", 
    subtitle = bquote( italic(R)^2 == .(df_metrics %>% dplyr::filter( sitename == "FR-Pue") %>% pull(.estimate))),
    y = expression(paste("GPP (gC m"^-2, "s"^-1, ")")), x = "MODIS EVI") +
  theme_classic() 

gg1 + gg2
ggsave("~/polybox/fig/gpp_evi.pdf", width = 8, height = 4)
```